libraries:              # Library mappings must have a colon (:) placed after them
  Movies:
    metadata_path:
      - file: config/Movies.yml
  TV Shows:
    metadata_path:
      - file: config/TV.yml
settings:                  # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  assets_for_all: false
  sync_mode: append
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  save_missing: true
  run_again_delay: 2
  missing_only_released: false
  create_asset_folders: false
  collection_minimum: 1
  delete_below_minimum: false
  tvdb_language: default
  show_missing_assets: true
  asset_depth: 0
  dimensional_asset_rename: false
  show_missing_season_assets: false
  delete_not_scheduled: false
  only_filter_missing: false
  show_options: false
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_user: all
plex:                       # Can be individually specified per library as well
  url: http://xxxxxxxxxxxxxxxxx
  token: xxxxxxxxxxxxxxxx
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:
  apikey: xxxxxxxxxxxxxxxxxxxxxx
  language: en
trakt:
  client_id: xxxxxxxxxxxxxxxxxxxxxxxxxx
  client_secret: xxxxxxxxxxxxxxxxxxxxxxxx
  authorization:
    access_token: xxxxxxxxxxxxxxxxxx
    token_type: xxxxxxxx
    expires_in: xxxxxxxxxxxxxxxxxx
    refresh_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    scope: public
    created_at: xxxxxxxxxxx