version: "3.7"
services:
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tbilisi
      - PMM_CONFIG=/config/config.yml #optional
      - PMM_TIME=03:00                #optional
      - PMM_RUN=False                 #optional
      - PMM_TEST=False                #optional
      - PMM_NO_MISSING=False          #optional
    volumes:
      - /opt/local/docker/config/plex-meta-manager:/config
    restart: unless-stopped

networks:
  nexus-proxy:
    driver: bridge
    external: true

#https://docs.ibracorp.io/plex-meta-manager-1/