version: "3.7
services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tbilisi
      - CHROME_CLI=https://www.linuxserver.io/ #optional
    shm_size: "1gb"
    volumes:
      - /opt/local/docker/config/chromium:/config
    ports:
      - 3080:3000
      - 3081:3001
    networks:
      - proxy-nexus
    restart: unless-stopped

networks:
  nexus-proxy:
    driver: bridge
    external: true